### ISSUE TITLE
[GeneticAlgorithm] NullPointerException

### ISSUE THREAD

**Issue by jose** [kanonizo/kanonizo#3]
Hi,

Steps to reproduce an unexpected NullPointerException:
```
$ mkdir /tmp/kanonizo_issue_3
$ cd /tmp/kanonizo_issue_3

# copy Chart-1b-coverage.txt to /tmp/kanonizo_issue_3

$ $D4J_HOME/defects4j checkout -p "Chart" -v "1b" -w "Chart-1b"
$ cd Chart-1b
$ $D4J_HOME/defects4j compile
$ cp=$($D4J_HOME/defects4j export -p cp.test)

$ java -cp "$cp:$KANONIZO_JAR" -javaagent:"$KANONIZO_JAR" org.kanonizo.Main -r /tmp/kanonizo_issue_3/Chart-1b -s build -t build-tests -Drandom_seed=0 -Dprioritise=true -Dscythe_read=true -Dlog_dir=ga -Dlog_filename=ga -Dscythe_filename=../Chart-1b-coverage.txt -Dclasses_per_group=1 -Duse_percentage_classes=false -a geneticalgorithm

...
INFO  org.kanonizo.algorithms.metaheuristics.GeneticAlgorithm - Generating initial population
ERROR org.kanonizo.Main - java.lang.NullPointerException
java.lang.NullPointerException
	at org.kanonizo.framework.objects.TestSuite.fitter(TestSuite.java:292)
	at org.kanonizo.framework.objects.TestSuite.compareTo(TestSuite.java:304)
	at org.kanonizo.framework.objects.TestSuite.compareTo(TestSuite.java:23)
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:325)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
	at java.util.Arrays.sort(Arrays.java:1246)
	at java.util.Arrays.sort(Arrays.java:1433)
	at java.util.Arrays$ArrayList.sort(Arrays.java:3895)
	at java.util.Collections.sort(Collections.java:141)
	at org.kanonizo.algorithms.metaheuristics.GeneticAlgorithm.getNFittest(GeneticAlgorithm.java:176)
	at org.kanonizo.algorithms.metaheuristics.GeneticAlgorithm.evolve(GeneticAlgorithm.java:126)
	at org.kanonizo.algorithms.TestSuitePrioritiser.generateSolution(TestSuitePrioritiser.java:73)
	at org.kanonizo.algorithms.AbstractSearchAlgorithm.start(AbstractSearchAlgorithm.java:106)
	at org.kanonizo.Framework.run(Framework.java:458)
	at org.kanonizo.Main.main(Main.java:69)
```

--
Best,
Jose

[Chart-1b-coverage.txt](https://github.com/kanonizo/kanonizo/files/2133698/Chart-1b-coverage.txt)

**Comment by mudasirhw** [comment]
i have an eror
ava.lang.NoClassDefFoundError: org/junit/runner/Runner
	at org.kanonizo.util.Util.isTestClass(Util.java:283)
	at org.kanonizo.Framework.loadClasses(Framework.java:267)
	at org.kanonizo.Framework.run(Framework.java:438)
	at org.kanonizo.Main.main(Main.java:101)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.Runner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
aa@aa-Latitude-3470:/tmp/lang_1_buggy$ java -jar $kanonizo_jar -s ./target/classes -t ./target/tests -a greedy [-l lib]

**Comment by djpaterson** [comment]
Hi @mudasirhw - it looks like you don't have JUnit installed in your maven repository. Kanonizo does not include a JUnit runtime in the jar that it builds because it is better to include the one on the client system. Try to install JUnit in your local maven repository `~/.m2/repository` and try again
