### ISSUE TITLE
Classloader issue?

### ISSUE THREAD

**Issue by alexdziena** [kanonizo/kanonizo#9]
Hi,

I'm getting an error when running Kanonizo on the [commons-math](https://github.com/apache/commons-math) repo.  To get Kanonizo to build, I needed to make some changes to the POM, including upgrading bcel to 6.5.0, removing the `<scope>provided</scope>` param for junit, and removing the system scope dependency for scythe (I installed scythe manually, and was getting NoClassDefFoundErrors with the system dependency in place).

```
$ java -jar target/kanonizo.jar -s ../../commons-math/target/classes -t ../../commons-math/target/test-classes -a greedy
...
10:14:36.829 [main] INFO  org.kanonizo.Framework - Added class org.apache.commons.math4.dfp.DfpField$RoundingMode
10:14:36.835 [main] INFO  org.kanonizo.Framework - Added class org.apache.commons.math4.dfp.DfpMath
10:14:36.839 [main] ERROR org.kanonizo.Framework - java.lang.NoClassDefFoundError: org/apache/commons/statistics/distribution/DiscreteDistribution
10:14:36.839 [main] ERROR org.kanonizo.Main - java.lang.NullPointerException
java.lang.NullPointerException
	at org.kanonizo.instrumenters.ScytheInstrumenter.getLines(ScytheInstrumenter.java:255)
	at org.kanonizo.framework.objects.ClassUnderTest.<init>(ClassUnderTest.java:19)
	at org.kanonizo.Framework.loadClasses(Framework.java:258)
	at org.kanonizo.Framework.run(Framework.java:438)
	at org.kanonizo.Main.main(Main.java:103)
```

**Comment by alexdziena** [comment]
This was resolved by manually installing the commons-statistics jar and referencing it with the -l flag, but I would have expected that to be picked up from commons-math classes.
